# Generated by Django 4.0.5 on 2022-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='raptor.jpg', upload_to='profilepics'),
        ),
    ]
