# Generated by Django 4.0.5 on 2022-06-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igclone', '0005_feed_comments_alter_comment_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igclone.feed'),
        ),
    ]
