# Generated by Django 4.0.5 on 2022-06-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igclone', '0007_feed_comments_alter_comment_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
    ]
