# Generated by Django 4.0.5 on 2022-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igclone', '0009_alter_comment_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='user_post', to='igclone.comment'),
        ),
    ]
